"""phase 10 persistence models

Revision ID: 0bdf50b0f98a
Revises: 0001_phase10_baseline
Create Date: 2026-09-11 09:34:20.967658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bdf50b0f98a'
down_revision: Union[str, None] = '0001_phase10_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('doc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    op.create_index(op.f('ix_datasets_sha256'), 'datasets', ['sha256'], unique=False)
    op.create_table('bom_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('material_id', sa.String(length=64), nullable=False),
    sa.Column('quantity_per_unit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_bom_items_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bom_items'))
    )
    op.create_index(op.f('ix_bom_items_dataset_id'), 'bom_items', ['dataset_id'], unique=False)
    op.create_table('boms',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_boms_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'product_id', name=op.f('pk_boms'))
    )
    op.create_index(op.f('ix_boms_dataset_id'), 'boms', ['dataset_id'], unique=False)
    op.create_table('calendar_day_shifts',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_calendar_day_shifts_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'day_index', 'shift_id', name=op.f('pk_calendar_day_shifts'))
    )
    op.create_index(op.f('ix_calendar_day_shifts_dataset_id'), 'calendar_day_shifts', ['dataset_id'], unique=False)
    op.create_table('calendar_days',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_calendar_days_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'day_index', name=op.f('pk_calendar_days'))
    )
    op.create_index(op.f('ix_calendar_days_dataset_id'), 'calendar_days', ['dataset_id'], unique=False)
    op.create_table('downtime_windows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=64), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_downtime_windows_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_downtime_windows'))
    )
    op.create_index(op.f('ix_downtime_windows_dataset_id'), 'downtime_windows', ['dataset_id'], unique=False)
    op.create_table('employee_shifts',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('shift_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_employee_shifts_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'employee_id', 'shift_id', name=op.f('pk_employee_shifts'))
    )
    op.create_index(op.f('ix_employee_shifts_dataset_id'), 'employee_shifts', ['dataset_id'], unique=False)
    op.create_table('employee_skills',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_employee_skills_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'employee_id', 'skill_id', name=op.f('pk_employee_skills'))
    )
    op.create_index(op.f('ix_employee_skills_dataset_id'), 'employee_skills', ['dataset_id'], unique=False)
    op.create_table('employee_work_centers',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=False),
    sa.Column('work_center_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_employee_work_centers_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'employee_id', 'work_center_id', name=op.f('pk_employee_work_centers'))
    )
    op.create_index(op.f('ix_employee_work_centers_dataset_id'), 'employee_work_centers', ['dataset_id'], unique=False)
    op.create_table('employees',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('available_from', sa.Integer(), nullable=False),
    sa.Column('available_until', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_employees_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'id', name=op.f('pk_employees'))
    )
    op.create_index(op.f('ix_employees_dataset_id'), 'employees', ['dataset_id'], unique=False)
    op.create_table('factories',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_factories_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', name=op.f('pk_factories'))
    )
    op.create_index(op.f('ix_factories_dataset_id'), 'factories', ['dataset_id'], unique=False)
    op.create_table('inventory',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=64), nullable=False),
    sa.Column('on_hand', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_inventory_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'material_id', name=op.f('pk_inventory'))
    )
    op.create_index(op.f('ix_inventory_dataset_id'), 'inventory', ['dataset_id'], unique=False)
    op.create_table('machines',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('work_center_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_machines_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'id', name=op.f('pk_machines'))
    )
    op.create_index(op.f('ix_machines_dataset_id'), 'machines', ['dataset_id'], unique=False)
    op.create_table('maintenance_windows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('machine_id', sa.String(length=64), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_maintenance_windows_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_windows'))
    )
    op.create_index(op.f('ix_maintenance_windows_dataset_id'), 'maintenance_windows', ['dataset_id'], unique=False)
    op.create_table('materials',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_materials_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'id', name=op.f('pk_materials'))
    )
    op.create_index(op.f('ix_materials_dataset_id'), 'materials', ['dataset_id'], unique=False)
    op.create_table('operation_machines',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('operation_id', sa.String(length=64), nullable=False),
    sa.Column('machine_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_operation_machines_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'operation_id', 'machine_id', name=op.f('pk_operation_machines'))
    )
    op.create_index(op.f('ix_operation_machines_dataset_id'), 'operation_machines', ['dataset_id'], unique=False)
    op.create_table('operations',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('work_center_id', sa.String(length=64), nullable=False),
    sa.Column('processing_time', sa.Integer(), nullable=False),
    sa.Column('setup_time', sa.Integer(), nullable=False),
    sa.Column('setup_family_id', sa.String(length=64), nullable=False),
    sa.Column('required_skill_id', sa.String(length=64), nullable=False),
    sa.Column('employee_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_operations_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'id', name=op.f('pk_operations'))
    )
    op.create_index(op.f('ix_operations_dataset_id'), 'operations', ['dataset_id'], unique=False)
    op.create_table('planning_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=36), nullable=True),
    sa.Column('objective', sa.String(length=64), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('result_status', sa.String(length=32), nullable=True),
    sa.Column('feasible', sa.Boolean(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('diagnostics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('root_cause', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_planning_runs_dataset_id_datasets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planning_runs'))
    )
    op.create_index(op.f('ix_planning_runs_dataset_id'), 'planning_runs', ['dataset_id'], unique=False)
    op.create_table('production_orders',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('release_time', sa.Integer(), nullable=False),
    sa.Column('due_time', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_production_orders_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'id', name=op.f('pk_production_orders'))
    )
    op.create_index(op.f('ix_production_orders_dataset_id'), 'production_orders', ['dataset_id'], unique=False)
    op.create_table('products',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_products_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_dataset_id'), 'products', ['dataset_id'], unique=False)
    op.create_table('routing_operations',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('routing_id', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_routing_operations_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'routing_id', 'position', name=op.f('pk_routing_operations'))
    )
    op.create_index(op.f('ix_routing_operations_dataset_id'), 'routing_operations', ['dataset_id'], unique=False)
    op.create_table('routings',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_routings_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'id', name=op.f('pk_routings'))
    )
    op.create_index(op.f('ix_routings_dataset_id'), 'routings', ['dataset_id'], unique=False)
    op.create_table('setup_matrix',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('from_family', sa.String(length=64), nullable=False),
    sa.Column('to_family', sa.String(length=64), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_setup_matrix_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'from_family', 'to_family', name=op.f('pk_setup_matrix'))
    )
    op.create_index(op.f('ix_setup_matrix_dataset_id'), 'setup_matrix', ['dataset_id'], unique=False)
    op.create_table('shifts',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_shifts_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'id', name=op.f('pk_shifts'))
    )
    op.create_index(op.f('ix_shifts_dataset_id'), 'shifts', ['dataset_id'], unique=False)
    op.create_table('skills',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_skills_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'id', name=op.f('pk_skills'))
    )
    op.create_index(op.f('ix_skills_dataset_id'), 'skills', ['dataset_id'], unique=False)
    op.create_table('work_centers',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_work_centers_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dataset_id', 'id', name=op.f('pk_work_centers'))
    )
    op.create_index(op.f('ix_work_centers_dataset_id'), 'work_centers', ['dataset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_centers_dataset_id'), table_name='work_centers')
    op.drop_table('work_centers')
    op.drop_index(op.f('ix_skills_dataset_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_shifts_dataset_id'), table_name='shifts')
    op.drop_table('shifts')
    op.drop_index(op.f('ix_setup_matrix_dataset_id'), table_name='setup_matrix')
    op.drop_table('setup_matrix')
    op.drop_index(op.f('ix_routings_dataset_id'), table_name='routings')
    op.drop_table('routings')
    op.drop_index(op.f('ix_routing_operations_dataset_id'), table_name='routing_operations')
    op.drop_table('routing_operations')
    op.drop_index(op.f('ix_products_dataset_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_production_orders_dataset_id'), table_name='production_orders')
    op.drop_table('production_orders')
    op.drop_index(op.f('ix_planning_runs_dataset_id'), table_name='planning_runs')
    op.drop_table('planning_runs')
    op.drop_index(op.f('ix_operations_dataset_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_operation_machines_dataset_id'), table_name='operation_machines')
    op.drop_table('operation_machines')
    op.drop_index(op.f('ix_materials_dataset_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_maintenance_windows_dataset_id'), table_name='maintenance_windows')
    op.drop_table('maintenance_windows')
    op.drop_index(op.f('ix_machines_dataset_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_inventory_dataset_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_factories_dataset_id'), table_name='factories')
    op.drop_table('factories')
    op.drop_index(op.f('ix_employees_dataset_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_employee_work_centers_dataset_id'), table_name='employee_work_centers')
    op.drop_table('employee_work_centers')
    op.drop_index(op.f('ix_employee_skills_dataset_id'), table_name='employee_skills')
    op.drop_table('employee_skills')
    op.drop_index(op.f('ix_employee_shifts_dataset_id'), table_name='employee_shifts')
    op.drop_table('employee_shifts')
    op.drop_index(op.f('ix_downtime_windows_dataset_id'), table_name='downtime_windows')
    op.drop_table('downtime_windows')
    op.drop_index(op.f('ix_calendar_days_dataset_id'), table_name='calendar_days')
    op.drop_table('calendar_days')
    op.drop_index(op.f('ix_calendar_day_shifts_dataset_id'), table_name='calendar_day_shifts')
    op.drop_table('calendar_day_shifts')
    op.drop_index(op.f('ix_boms_dataset_id'), table_name='boms')
    op.drop_table('boms')
    op.drop_index(op.f('ix_bom_items_dataset_id'), table_name='bom_items')
    op.drop_table('bom_items')
    op.drop_index(op.f('ix_datasets_sha256'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
